# Config file for automatic testing at travis-ci.org

language: python
sudo: false

python:
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"

install:
    - travis_retry pip install -U pytest mock responses
    - pip install -U .
script: python setup.py test
